var metadata=
{
   "local-cache":[
      {
         "name":"dbConfigCache",
         "start":"EAGER",
         "eviction":{
            "strategy":"LIRS",
            "type":"COUNT",
            "size":"10"
         },
         "expiration":{
            "lifespan":"86400000"
         }
      },
      {
         "name":"clientByMIDCache",
         "start":"EAGER",
         "eviction":{
            "strategy":"LIRS",
            "type":"COUNT",
            "size":"10000"
         },
         "expiration":{
            "lifespan":"86400000"
         }
      },
      {
         "name":"pgsecureinfoCache",
         "start":"EAGER",
         "eviction":{
            "strategy":"LIRS",
            "type":"COUNT",
            "size":"40000"
         },
         "expiration":{
            "lifespan":"86400000"
         }
      },
      {
         "name":"webpayBanksInfocache",
         "start":"EAGER",
         "eviction":{
            "strategy":"LIRS",
            "type":"COUNT",
            "size":"200"
         },
         "expiration":{
            "lifespan":"86400000"
         }
      },
      {
         "name":"sbiBanksInfocache",
         "start":"EAGER",
         "eviction":{
            "strategy":"LIRS",
            "type":"COUNT",
            "size":"100"
         },
         "expiration":{
            "lifespan":"86400000"
         }
      },
      {
         "name":"sbiBankMappingCodes",
         "start":"EAGER",
         "eviction":{
            "strategy":"LIRS",
            "type":"COUNT",
            "size":"200"
         },
         "expiration":{
            "lifespan":"86400000"
         }
      },
      {
         "name":"billldeskBankMappingCodes",
         "start":"EAGER",
         "eviction":{
            "strategy":"LIRS",
            "type":"COUNT",
            "size":"200"
         },
         "expiration":{
            "lifespan":"86400000"
         }
      },
      {
         "name":"iciciBankMappingCodes",
         "start":"EAGER",
         "eviction":{
            "strategy":"LIRS",
            "type":"COUNT",
            "size":"200"
         },
         "expiration":{
            "lifespan":"86400000"
         }
      },
      {
         "name":"domesticBinCache",
         "start":"EAGER",
         "eviction":{
            "strategy":"LIRS",
            "type":"COUNT",
            "size":"200"
         },
         "expiration":{
            "lifespan":"86400000"
         }
      },
      {
         "name":"convenienceFeeCache",
         "start":"EAGER",
         "eviction":{
            "strategy":"LIRS",
            "type":"COUNT",
            "size":"10000"
         },
         "expiration":{
            "lifespan":"86400000"
         }
      },
      {
         "name":"nonAggregratorBankCodes",
         "start":"EAGER",
         "eviction":{
            "strategy":"LIRS",
            "type":"COUNT",
            "size":"100"
         },
         "expiration":{
            "lifespan":"86400000"
         }
      },
      {
         "name":"mgrpCache",
         "start":"EAGER",
         "eviction":{
            "strategy":"LIRS",
            "type":"COUNT",
            "size":"100"
         },
         "expiration":{
            "lifespan":"86400000"
         }
      },
      {
         "name":"altPmtProcCache",
         "start":"EAGER",
         "eviction":{
            "strategy":"LIRS",
            "type":"COUNT",
            "size":"25"
         },
         "expiration":{
            "lifespan":"86400000"
         }
      },
      {
         "name":"affBanksCache",
         "start":"EAGER",
         "eviction":{
            "strategy":"LIRS",
            "type":"COUNT",
            "size":"50"
         },
         "expiration":{
            "lifespan":"86400000"
         }
      },
      {
         "name":"pmtProcsCache",
         "start":"EAGER",
         "eviction":{
            "strategy":"LIRS",
            "type":"COUNT",
            "size":"50"
         },
         "expiration":{
            "lifespan":"86400000"
         }
      },
      {
         "name":"routingRulesCache",
         "start":"EAGER",
         "eviction":{
            "strategy":"LIRS",
            "type":"COUNT",
            "size":"10000"
         },
         "expiration":{
            "lifespan":"86400000"
         }
      },
      {
         "name":"historicRulesCache",
         "start":"EAGER",
         "eviction":{
            "strategy":"LIRS",
            "type":"COUNT",
            "size":"10000"
         },
         "expiration":{
            "lifespan":"86400000"
         }
      },
      {
         "name":"bankRestrictCache",
         "start":"EAGER",
         "eviction":{
            "strategy":"LIRS",
            "type":"COUNT",
            "size":"1000"
         },
         "expiration":{
            "lifespan":"86400000"
         }
      },
      {
         "name":"errcodesmsgs",
         "start":"EAGER",
         "eviction":{
            "strategy":"LIRS",
            "type":"COUNT",
            "size":"1000"
         },
         "expiration":{
            "lifespan":"86400000"
         }
      },
      {
         "name":"issuererrcodesmsgs",
         "start":"EAGER",
         "eviction":{
            "strategy":"LIRS",
            "type":"COUNT",
            "size":"1000"
         },
         "expiration":{
            "lifespan":"86400000"
         }
      },
      {
         "name":"payUBankMappingCodes",
         "start":"EAGER",
         "eviction":{
            "strategy":"LIRS",
            "type":"COUNT",
            "size":"200"
         },
         "expiration":{
            "lifespan":"86400000"
         }
      },
      {
         "name":"payUErrMsg",
         "start":"EAGER",
         "eviction":{
            "strategy":"LIRS",
            "type":"COUNT",
            "size":"200"
         },
         "expiration":{
            "lifespan":"86400000"
         }
      },
      {
         "name":"paymentTypesCache",
         "start":"EAGER",
         "eviction":{
            "strategy":"LIRS",
            "type":"COUNT",
            "size":"10000"
         },
         "expiration":{
            "lifespan":"86400000"
         }
      },
      {
         "name":"cardbinmaster",
         "start":"EAGER",
         "eviction":{
            "strategy":"LIRS",
            "type":"COUNT",
            "size":"10000"
         },
         "expiration":{
            "lifespan":"86400000"
         }
      },
      {
         "name":"timeoutsByAPI",
         "start":"EAGER",
         "eviction":{
            "strategy":"LIRS",
            "type":"COUNT",
            "size":"1000"
         },
         "expiration":{
            "lifespan":"86400000"
         }
      },
      {
         "name":"secured-convenience",
         "start":"EAGER",
         "eviction":{
            "strategy":"LIRS",
            "type":"COUNT",
            "size":"10000"
         },
         "expiration":{
            "lifespan":"86400000"
         }
      },
      {
         "name":"wpcache",
         "start":"EAGER",
         "eviction":{
            "strategy":"LIRS",
            "type":"COUNT",
            "size":"1000"
         },
         "expiration":{
            "lifespan":"86400000"
         }
      },
      {
         "name":"istResponseTextCache",
         "start":"EAGER",
         "eviction":{
            "strategy":"LIRS",
            "type":"COUNT",
            "size":"1000"
         },
         "expiration":{
            "lifespan":"86400000"
         }
      }
   ],
   "distributed-cache":[
      {
         "name":"default",
         "mode":"SYNC",
         "segments":"20",
         "owners":"2",
         "remote-timeout":"30000",
         "start":"EAGER",
         "locking":{
            "acquire-timeout":"30000",
            "concurrency-level":"1000",
            "striping":"false"
         },
         "transaction":{
            "mode":"NONE"
         }
      },
      {
         "name":"txnDataCache",
         "mode":"SYNC",
         "segments":"20",
         "owners":"2",
         "remote-timeout":"30000",
         "start":"EAGER",
         "locking":{
            "acquire-timeout":"30000",
            "concurrency-level":"1000",
            "striping":"false"
         },
         "transaction":{
            "mode":"NONE"
         },
         "eviction":{
            "strategy":"LIRS",
            "type":"COUNT",
            "size":"1000000"
         },
         "expiration":{
            "lifespan":"600000"
         }
      },
      {
         "name":"paymentTypesCache",
         "mode":"SYNC",
         "segments":"20",
         "owners":"2",
         "remote-timeout":"30000",
         "start":"EAGER",
         "locking":{
            "acquire-timeout":"30000",
            "concurrency-level":"1000",
            "striping":"false"
         },
         "transaction":{
            "mode":"NONE"
         },
         "eviction":{
            "strategy":"LIRS",
            "type":"COUNT",
            "size":"10000"
         },
         "expiration":{
            "lifespan":"86400000"
         }
      },
      {
         "name":"txnStatusByExtRefCache",
         "mode":"SYNC",
         "segments":"20",
         "owners":"2",
         "remote-timeout":"30000",
         "start":"EAGER",
         "locking":{
            "acquire-timeout":"30000",
            "concurrency-level":"1000",
            "striping":"false"
         },
         "transaction":{
            "mode":"NONE"
         },
         "eviction":{
            "strategy":"LIRS",
            "type":"COUNT",
            "size":"2000000"
         },
         "expiration":{
            "lifespan":"3600000"
         }
      },
      {
         "name":"clientinfoCache",
         "mode":"SYNC",
         "segments":"20",
         "owners":"2",
         "remote-timeout":"30000",
         "start":"EAGER",
         "locking":{
            "acquire-timeout":"30000",
            "concurrency-level":"1000",
            "striping":"false"
         },
         "transaction":{
            "mode":"NONE"
         },
         "eviction":{
            "strategy":"LIRS",
            "type":"COUNT",
            "size":"10000"
         },
         "#text":"Expiration 24 hours for (mostly) static data",
         "expiration":{
            "lifespan":"86400000"
         }
      },
      {
         "name":"txnStatusByinterRefCache",
         "mode":"SYNC",
         "segments":"20",
         "owners":"2",
         "remote-timeout":"30000",
         "start":"EAGER",
         "locking":{
            "acquire-timeout":"30000",
            "concurrency-level":"1000",
            "striping":"false"
         },
         "transaction":{
            "mode":"NONE"
         },
         "eviction":{
            "strategy":"LIRS",
            "type":"COUNT",
            "size":"1000"
         },
         "expiration":{
            "lifespan":"180000"
         }
      },
      {
         "name":"failCountCache",
         "mode":"SYNC",
         "segments":"20",
         "owners":"2",
         "remote-timeout":"30000",
         "start":"EAGER",
         "locking":{
            "acquire-timeout":"30000",
            "concurrency-level":"1000",
            "striping":"false"
         },
         "transaction":{
            "mode":"NONE"
         },
         "eviction":{
            "strategy":"LIRS",
            "type":"COUNT",
            "size":"100000"
         },
         "expiration":{
            "lifespan":"1800000"
         }
      },
      {
         "name":"pmt_proc_resp_cache_region",
         "mode":"SYNC",
         "segments":"20",
         "owners":"2",
         "remote-timeout":"30000",
         "start":"EAGER",
         "locking":{
            "acquire-timeout":"30000",
            "concurrency-level":"1000",
            "striping":"false"
         },
         "transaction":{
            "mode":"NONE"
         },
         "eviction":{
            "strategy":"LIRS",
            "type":"COUNT",
            "size":"1000000"
         },
         "expiration":{
            "lifespan":"300000"
         }
      },
      {
         "name":"pmt_proc_req_cache_region",
         "mode":"SYNC",
         "segments":"20",
         "owners":"2",
         "remote-timeout":"30000",
         "start":"EAGER",
         "locking":{
            "acquire-timeout":"30000",
            "concurrency-level":"1000",
            "striping":"false"
         },
         "transaction":{
            "mode":"NONE"
         },
         "eviction":{
            "strategy":"LIRS",
            "type":"COUNT",
            "size":"1000000"
         },
         "expiration":{
            "lifespan":"3600000"
         }
      },
      {
         "name":"oneclicks2scache",
         "mode":"SYNC",
         "segments":"20",
         "owners":"2",
         "remote-timeout":"30000",
         "start":"EAGER",
         "locking":{
            "acquire-timeout":"30000",
            "concurrency-level":"1000",
            "striping":"false"
         },
         "transaction":{
            "mode":"NONE"
         },
         "eviction":{
            "strategy":"LIRS",
            "type":"COUNT",
            "size":"1000"
         },
         "expiration":{
            "lifespan":"1800000"
         }
      },
      {
         "name":"mpinStatCache",
         "mode":"SYNC",
         "segments":"20",
         "owners":"2",
         "remote-timeout":"30000",
         "start":"EAGER",
         "locking":{
            "acquire-timeout":"30000",
            "concurrency-level":"1000",
            "striping":"false"
         },
         "transaction":{
            "mode":"NONE"
         },
         "eviction":{
            "strategy":"LIRS",
            "type":"COUNT",
            "size":"10000"
         },
         "expiration":{
            "lifespan":"1800000"
         }
      },
      {
         "name":"b2b_pmt_proc_resp_cache",
         "mode":"SYNC",
         "segments":"20",
         "owners":"2",
         "remote-timeout":"30000",
         "start":"EAGER",
         "locking":{
            "acquire-timeout":"30000",
            "concurrency-level":"1000",
            "striping":"false"
         },
         "transaction":{
            "mode":"NONE"
         },
         "eviction":{
            "strategy":"LIRS",
            "type":"COUNT",
            "size":"2000000"
         },
         "expiration":{
            "lifespan":"1800000"
         }
      },
      {
         "name":"s2s_pmt_proc_resp_cache",
         "mode":"SYNC",
         "segments":"20",
         "owners":"2",
         "remote-timeout":"30000",
         "start":"EAGER",
         "locking":{
            "acquire-timeout":"30000",
            "concurrency-level":"1000",
            "striping":"false"
         },
         "transaction":{
            "mode":"NONE"
         },
         "eviction":{
            "strategy":"LIRS",
            "type":"COUNT",
            "size":"2000000"
         },
         "expiration":{
            "lifespan":"1800000"
         }
      },
      {
         "name":"SHORT_CASH_LOAD_MONEY",
         "mode":"SYNC",
         "segments":"20",
         "owners":"2",
         "remote-timeout":"30000",
         "start":"EAGER",
         "locking":{
            "acquire-timeout":"30000",
            "concurrency-level":"1000",
            "striping":"false"
         },
         "transaction":{
            "mode":"NONE"
         },
         "expiration":{
            "lifespan":"60000"
         }
      },
      {
         "name":"panDetailsCache",
         "mode":"SYNC",
         "segments":"20",
         "owners":"2",
         "remote-timeout":"30000",
         "start":"EAGER",
         "locking":{
            "acquire-timeout":"30000",
            "concurrency-level":"1000",
            "striping":"false"
         },
         "transaction":{
            "mode":"NONE"
         },
         "eviction":{
            "strategy":"LIRS",
            "type":"COUNT",
            "size":"10000"
         },
         "expiration":{
            "lifespan":"900000"
         }
      },
      {
         "name":"userDetailsCache",
         "mode":"SYNC",
         "segments":"20",
         "owners":"2",
         "remote-timeout":"30000",
         "start":"EAGER",
         "locking":{
            "acquire-timeout":"30000",
            "concurrency-level":"1000",
            "striping":"false"
         },
         "transaction":{
            "mode":"NONE"
         },
         "eviction":{
            "strategy":"LIRS",
            "type":"COUNT",
            "size":"10000"
         },
         "expiration":{
            "lifespan":"900000"
         }
      }
   ]
}